---
title: "Trabajo Final"
lang: es
date: "`r Sys.Date()`"
author:
  - Kevin Jay Herrera [kjayh@unal.edu.co]
  - c.c 1007340307
  - Omar Chavez
  - c.c
  - Yesid Lopez
  - c.c
format: 
  html:
    toc: true
    self-contained: true
editor: visual
execute: 
  echo: false
  warning: false
  message: false
---

## Base de datos

Resumen de la base de datos E-14

```{r}

rm(list = ls())
```

```{r}
library(readxl)
library(sf)
library(tidyverse)
```

```{r}
# Lectura de la base de datos.
datos_E_14 <- read.csv("./datos/datos(E-14).csv", stringsAsFactors = TRUE)

icfes <- read.csv("./datos/Saber_11__2020-2.csv", stringsAsFactors = TRUE)
```

You can add options to executable code like this

```{r}
puestos <- (c(datos_E_14$nombrePuesto))
split(datos_E_14,puestos)
$

puestos <- (c(datos_E_14$nombrePuesto))
split(datos_E_14,puestos)
$

#| echo: false
barrios <- read_sf("barrios/BarrioVereda_2014.shp")
```

```{r}
plot(st_geometry(barrios))
```

```{r}
puestos_votacion <- read_excel("datos/medellin_coordenadas_original.xlsx")
```

```{r}
puestos_votacion_sf <- st_as_sf(puestos_votacion,
                                coords = c("longitud", "latitud"),
                                crs = 4326 )
```

```{r}
plot(st_geometry(puestos_votacion_sf))
```

```{r}
ggplot(barrios) +
  geom_sf()
```

```{r}
puestos_votacion_sf_barrio <- puestos_votacion_sf %>% 
  st_join(barrios)
```

```{r}
head(puestos_votacion_sf_barrio)
```
